### ISSUE TITLE
Can't load it in ABCL

### ISSUE THREAD

**Issue by catap** [wlbr/cl-marshal#17]
```
:info:build ; (IN-PACKAGE :CL-USER)
:info:build Caught PACKAGE-ERROR while processing --eval option "(asdf:operate (quote asdf:build-op) (quote marshal-tests))":
:info:build   A symbol named TEST is already accessible in package COMMON-LISP-USER.
:info:build Command failed: env XDG_CACHE_HOME=$HOME/.cache /opt/local/bin/abcl --noinit --batch --eval '(require "asdf")' --eval '(setf asdf:*central-registry* (list* (quote *default-pathname-defaults*) #p"/opt/local/var/macports/build/_Users_catap_src_macports-ports_lisp_cl-marshal/cl-marshal/work/build/system/" #p"/opt/local/share/common-lisp/system/" asdf:*central-registry*))' --eval '(asdf:operate (quote asdf:build-op) (quote marshal-tests))' 2>&1
```

**Comment by cage2** [comment]
Hi @catap !

Unfortunately I'll be very busy for the next 7/10 days, I'll try to investigate the issue after a week or so. In the meanwhile, please can you check if you are able to load `xlunit`, the unit test suite this package uses?

Thanks in advance!
C.

**Comment by catap** [comment]
@cage2 yes, it works well

**Comment by cage2** [comment]
Hi @catap !

This is a good starting point! Please be patient, I'll try to fix the code ASAP but very unlikely i am going to have the chance to take a good look at the code in the next 7 days. 

Thanks!
C.

**Comment by catap** [comment]
np, take your time!

**Comment by cage2** [comment]
Hi @catap !

Turned out that a bunch of problems prevented the library to be loaded on ABCL.

I believe the last version from this repository should fix the issue.

There is another, still unsolved, problem that prevents ABCL to de-serialize deeply nested object but i would say that they are pathologically nested object and not a big issue, for the moment. But i would like to investigate this problem later. 

Thanks you very much for your report!

Feel free to close this bug report if the patch solve the problem you pointed out.
Bye!

**Comment by catap** [comment]
Thanks, it works!
